### ISSUE TITLE
merge Preperation + Welcome

### ISSUE THREAD

**Issue by star-buck** [calamares/calamares-todos#11]

**Comment by teo** [comment]
This is indeed doable, and I've already started working on it. It requires some major intervention in both the prepare and greeting viewmodules, so I'm taking advantage of the occasion to do some much needed UX design improvements. Ideally, we should have less text, fewer pages and smarter defaults.

**Comment by star-buck** [comment]
this can be closed?

**Comment by teo** [comment]
Yes, it most definitely can.
