### ISSUE TITLE
[Partitions]: show before and after partition preview (like ubiquity) for first three options (all but "Manual") directly on that page

### ISSUE THREAD

**Issue by star-buck** [calamares/calamares-todos#12]

**Comment by teo** [comment]
* The Erase option already has the before/after preview, it shows up once the user selects a drive. The placement of everything could be improved though.
* The Alongside option only has the shrink widget. If we had 2 bars, we would need to comunicate clearly that one is an input widget and the other is not, which is a potential UX problem. I can look into how feasible this is.
* The Replace page does not change the partitioning layout, it only formats a single partition (so there is a single preview bar). If there were 2 bars, they would look the same.

Were you thinking of adding those previews back on the Choice page? Or just making sure each page has its own 2-bar preview?
The former is problematic with our current KPM submodule, but I can investigate the latter.

**Comment by teo** [comment]
The preview widget has changed over the past 2 weeks, with labels for each bar and improved coloring. Please let me know if there are still parts of this TODO item that need to be implemented.
