### ISSUE TITLE
List of small fixes

### ISSUE THREAD

**Issue by star-buck** [calamares/calamares-todos#13]
About:
Change text "technologies for a better world" to "Liberating Software."
![about](https://cloud.githubusercontent.com/assets/840070/7185363/83705728-e462-11e4-8369-6e65ab943f73.png)

Partitions:
Yellow Warning sign traingle is missing the "!" inside
Move "Erase disk" to third position below "Replace" and start with "Alongside"
![icons-screenshot](https://cloud.githubusercontent.com/assets/840070/7185364/83740814-e462-11e4-9d31-01d8f213a4bd.png)

Summary:
Colors of a newly created or replaced partition should be different (like pink in the lower bar instead of green):
![summary](https://cloud.githubusercontent.com/assets/840070/7185365/8378f46e-e462-11e4-9e8e-6d6450153e22.png)

**Comment by teo** [comment]
(1) and (2) are fixed in master.

**Comment by teo** [comment]
Exclamation mark is now fixed in master (thanks to Jens).

**Comment by teo** [comment]
The colors issue (3) is now fixed in master.
