### ISSUE TITLE
SWAP-Partition likely not correctly setup when replacing or alongside installing a new OS with calamares 1.1.2

### ISSUE THREAD

**Issue by star-buck** [calamares/calamares-todos#14]
the same boot delay happens when using netrunner rolling 2015.06 pre3 and installing it alongside a netrunner 16 already on the disk:
https://forums.opensuse.org/showthread.php/503587-Slow-boot-What-is-quot-A-start-job-is-running-for-dev-disk-by-quot?p=2684683#post2684683

**Comment by teo** [comment]
It could indeed be a swap issue. I could use some more information on this. If you still have that setup, could you please paste me the contents of `/etc/fstab`, and the output of `lsblk`?

**Comment by teo** [comment]
This should be fixed as of last week, since the UUID of swap partitions is now preserved even when formatting.
