### ISSUE TITLE
using calamares as POST-Install tool for ARM-environments

### ISSUE THREAD

**Issue by star-buck** [calamares/calamares-todos#15]
using calamares as a config-tool on ARM-flashed devices (POST-Install or PRE-install+flasher):

0.1 demo:
* set locale
* set keyboard

0.2 milestones:
* add new user (different from root)
* change root-password
* mmc/sd card resize (using e.g. odroids own script: fs_resize)

**Comment by teo** [comment]
Closing this since it's supported on the Calamares side, and Rohan is in charge.
