### ISSUE TITLE
calamares doesnt offer "install alongside" option on a disk with just kubuntu freshly installed

### ISSUE THREAD

**Issue by star-buck** [calamares/calamares-todos#16]

**Comment by AJSlye** [comment]
I have the same issue with Manjaro Installations that were installed with thus.
On Manjaro, thus installs /boot on a ext2 partition so maybe this has to do with the e2fsprogs issue as well. https://calamares.io/Important-e2fsprogs-issue-discovered/

**Comment by star-buck** [comment]
hopefully fixed with 2.0, will close for now
