### ISSUE TITLE
calamares 1.1.3: "install alongside" fails to create partition

### ISSUE THREAD

**Issue by star-buck** [calamares/calamares-todos#17]
This image has been taken after calamares failed to install a partition in the grey free space area, which it shrank before (so this screenshot is after havbing started calamares again a second time now wanting to shrink the first partition again in half...): 
![calamares](https://cloud.githubusercontent.com/assets/840070/10105490/3b038e48-63af-11e5-921a-84c4addea1cd.png)

**Comment by teo** [comment]
Fixed in 1.1.4, released today.
