### ISSUE TITLE
[partition]: show options 'alongside' or 'replace' when only one system is installed

### ISSUE THREAD

**Issue by star-buck** [calamares/calamares-todos#19]
At least replace should ALWAYS be possible and therefore shown:
![calamares](https://cloud.githubusercontent.com/assets/840070/11790898/282e9cec-a296-11e5-9a21-97b436813eaa.png)

**Comment by philmmanjaro** [comment]
Always use the debug mode and post a full install log so we can debug it more:
```
sudo calamares -d
```
It always depends what Calamares detects. For analysis the full detected partition layout would be helpful.

**Comment by teo** [comment]
I assume this might be the same situation as #20

**Comment by star-buck** [comment]
beta1:
the options are now initially shown, but once you move forward past the partition page and then back, they dissappear.

**Comment by star-buck** [comment]
v1.92:

still shows this while it has only 1xnetrunner rolling installed:
![screenshot_20160101_195958](https://cloud.githubusercontent.com/assets/840070/12071999/455b0f1e-b0c2-11e5-9acd-83b7ff6ce74a.png)

Also mounts the harddrive as sdb, and stick as sda, which is confusing as sda device is selected default and therefore uninitiated users might mot notice this right away...

[netrunner@netrunner ~]$ sudo calamares -d
19:54:57 [1]: Calamares version: 1.92.0 
Translation: Calamares: Using system locale: "en_US"
Translation: Qt: Using default locale, system locale one not found: "en_US"
19:54:57 [1]: Default font ===== 
Pixel size:    -1 
Point size:    9 
Point sizeF:   9 
Font family:   "Sans Serif" 
Metric height: 14 
19:54:57 [1]: Font height: 14 
19:54:57 [1]: Available languages: ("ar", "ast", "ca", "cs_CZ", "da", "de", "en", "en_GB", "es_MX", "es", "fi_FI", "fr", "hr", "hu", "id", "it_IT", "ja", "lt", "nl", "pl", "pt_BR", "pt_PT", "ro", "ru", "sk", "sl", "sv", "th", "tr_TR", "zh_CN", "zh_TW") 
19:54:57 [1]: CalamaresApplication thread: 0x2656ab0 
19:54:57 [1]: Using Calamares settings file at "/usr/share/calamares/settings.conf" 
19:54:57 [1]: Using Calamares branding file at "/usr/share/calamares/branding/netrunner-rolling/branding.desc" 
19:54:57 [1]: WARNING: the selected branding component does not ship translations. 
19:54:57 [1]: Loaded branding component "netrunner-rolling" 
19:54:57 [1]: Proposed window size: 1010 520 
19:54:57 [1]: Initial locale  "en_US" 
19:54:57 [8]: Translation: Calamares: Using system locale: "en_US"
19:54:57 [8]: Translation: Qt: Using default locale, system locale one not found: "en_US"
19:54:57 [1]: ViewModule loading self for instance "welcome@welcome" 
ViewModule at address 0x2821990 
Calamares::PluginFactory at address WelcomeViewStepFactory(0x272e830) 
ViewStep at address WelcomeViewStep(0x28282f0) 
19:54:57 [1]: ViewModule loading self for instance "locale@locale" 
ViewModule at address 0x2881210 
Calamares::PluginFactory at address LocaleViewStepFactory(0x284e6b0) 
ViewStep at address LocaleViewStep(0x2880ec0) 
No layout variant specified on the command line
Trailing -variant option ignored
19:54:57 [1]: xkbmap selection changed to:  "us" - "" 
19:54:57 [1]: ViewModule loading self for instance "keyboard@keyboard" 
ViewModule at address 0x288a0a0 
Calamares::PluginFactory at address KeyboardViewStepFactory(0x288a5f0) 
ViewStep at address KeyboardViewStep(0x2889e90) 
19:54:57 [8]: Loaded backend plugin:  "pmlibpartedbackendplugin"
19:54:57 [8]: getting smart status failed for  "/dev/sda" :  Operation not supported
19:54:57 [0]: QFileInfo::absolutePath: Constructed with empty filename
19:54:58 [0]: QFileInfo::absolutePath: Constructed with empty filename
19:54:58 [0]: QFileInfo::absolutePath: Constructed with empty filename
19:54:59 [1]: checking if "/dev/sdb2" can be resized. 
19:54:59 [1]: "/dev/sdb2" seems like a good path 
19:54:59 [1]: found Partition* for "/dev/sdb2" 
19:54:59 [1]: Required  storage B: 8160437862 "(7GB)" 
19:54:59 [1]: Available storage B: 957305760256 "(891GB)" 
19:54:59 [1]: Partition "/dev/sdb2" authorized for resize + autopartition install. 
19:54:59 [1]: "Osprober lines, clean:\n/dev/sdb2:Netrunner Rolling (next-dev3):Netrunner:linux" 
19:54:59 [1]: ViewModule loading self for instance "partition@partition" 
ViewModule at address 0x28e4ce0 
Calamares::PluginFactory at address PartitionViewStepFactory(0x28f0430) 
ViewStep at address PartitionViewStep(0x28e9850) 
19:54:59 [1]: ViewModule loading self for instance "users@users" 
ViewModule at address 0x294fa50 
Calamares::PluginFactory at address UsersViewStepFactory(0x294f9f0) 
ViewStep at address UsersViewStep(0x29504f0) 
19:54:59 [1]: ViewModule loading self for instance "summary@summary" 
ViewModule at address 0x2978270 
Calamares::PluginFactory at address SummaryViewStepFactory(0x2978660) 
ViewStep at address SummaryViewStep(0x2978780) 
19:54:59 [1]: Module "partition@partition" already loaded. 
19:54:59 [1]: QML import paths: ("/usr/share/calamares/qml", "/usr/bin", "/usr/lib/qt/qml") 
19:54:59 [1]: LAST VS IS EVS! 
19:54:59 [1]: LAST VS IS EVS! 
19:54:59 [1]: LAST VS IS EVS! 
19:54:59 [1]: LAST VS IS EVS! 
19:54:59 [1]: Module "locale@locale" already loaded. 
19:54:59 [1]: LAST VS IS EVS! 
19:54:59 [1]: Module "keyboard@keyboard" already loaded. 
19:54:59 [1]: LAST VS IS EVS! 
19:54:59 [1]: LAST VS IS EVS! 
19:54:59 [1]: LAST VS IS EVS! 
19:54:59 [1]: LAST VS IS EVS! 
19:54:59 [1]: Module "users@users" already loaded. 
19:54:59 [1]: LAST VS IS EVS! 
19:54:59 [1]: LAST VS IS EVS! 
19:54:59 [1]: LAST VS IS EVS! 
19:54:59 [1]: LAST VS IS EVS! 
19:54:59 [1]: LAST VS IS EVS! 
19:54:59 [1]: LAST VS IS EVS! 
19:54:59 [1]: LAST VS IS EVS! 
19:54:59 [1]: LAST VS IS EVS! 
19:54:59 [1]: LAST VS IS EVS! 
19:54:59 [1]: LAST VS IS EVS! 
19:54:59 [1]: ViewModule loading self for instance "finished@finished" 
ViewModule at address 0x2a1c310 
Calamares::PluginFactory at address FinishedViewStepFactory(0x2a175d0) 
ViewStep at address FinishedViewStep(0x2a1a120) 
19:54:59 [1]: Need at least storage bytes: 5905580032 
19:54:59 [1]: Need at least ram bytes: 1073741824 
19:54:59 [1]: enoughStorage, enoughRam, hasPower, hasInternet, isRoot:  true true true true true 
19:54:59 [1]: Updating partitioning state widgets. 
19:54:59 [0]: QCoreApplication::postEvent: Unexpected null receiver
19:54:59 [8]: getting smart status failed for  "/dev/sda" :  Operation not supported
19:54:59 [0]: QFileInfo::absolutePath: Constructed with empty filename
19:54:59 [1]: Updating partitioning preview widgets. 
19:54:59 [0]: QCoreApplication::postEvent: Unexpected null receiver
19:54:59 [1]: Current index changed: "/dev/sdb2" 
19:54:59 [0]: QFileInfo::absolutePath: Constructed with empty filename
19:54:59 [0]: QFileInfo::absolutePath: Constructed with empty filename
19:54:59 [1]: PSI added item "" size 2080256 
19:54:59 [1]: PSI added item "/dev/sdb1" size 314573312 
19:54:59 [1]: PSI added item "/dev/sdb2" size 990436674048 
19:54:59 [1]: PSI added item "/dev/sdb3" size 9448928256 
19:54:59 [1]: PSI added item "" size 2595840 
19:54:59 [1]: void PartitionSplitterWidget::setSplitPartition(const QString&, qint64, qint64, qint64, const QString&) path: "/dev/sdb2" 
minSize: 36444005171 
maxSize: 982276236186 
prfSize: 495218337024 
19:54:59 [1]: itemToResize: "/dev/sdb2" 
19:54:59 [1]: Items updated. Status: 
19:54:59 [1]: item "" size 2080256 
19:54:59 [1]: item "/dev/sdb1" size 314573312 
19:54:59 [1]: item "/dev/sdb2" size 495218337024 
19:54:59 [1]: item "" size 495218337024 
19:54:59 [1]: item "/dev/sdb3" size 9448928256 
19:54:59 [1]: item "" size 2595840

**Comment by star-buck** [comment]
its also double confusing here, as the bottloader again is suggested to be put on sda, which should be sdb then at least according to which device you picked to overall install the OS.
![screenshot_20160101_200359](https://cloud.githubusercontent.com/assets/840070/12072007/f78b688c-b0c2-11e5-81b1-7d05a89cb83c.png)

The blue color also looks like it is appended at the end (see closely "Before").
Things to improve would be to 

* logically display the sdb1 with the same pixels as sdb3 (so lets have a minimum pixel width of 5 pixels here no matter the actual size of the partition)
* show sdb1 bootloader colored bar in order at the beginning
* show the to-be-installed bootloader in the "After" bar also colored at the beginning.

**Comment by star-buck** [comment]
it should at least show replace in the scenario above

**Comment by philmmanjaro** [comment]
Hi Clemens,

what does **parted**, **fdisk** or the **partitionmanager** show you on this machine. It seems to be a local problem on your PC that your USB-Stick get detected as **sda** device. Maybe change the order of your hard drives in your **BIOS** ore **EFI** settings. What kind of hard drive is it anyway? **IDE**, **SCSI**, **SATA**, **External USB** ? I also suggest to create some Virtual Machines with several hardware settings to test more. One with BIOS setup and several hard drives mounted, one with EFI setup and so on. If possible check also another PC, Laptop to compare how it works as in the current one.

Adding where the bootloader gets installed might make sense in type of usability and point of user view, more or less not view of technical partitioning. However, lets think about how that might get integrated properly.

**Comment by teo** [comment]
@star-buck I'm looking into these.
Regarding the stick being sda and internal drive being sdb, there's nothing Calamares can do about this since it's completely up to the kernel and udev. Device nodes are created as needed depending on which device comes up first, and in this case I assume the stick got picked up before the internal drive. That's what persistent device naming is for, but it yields longer paths (e.g. `/dev/disk/by-id/ata-KINGSTON_SH103S3240G_50026B722C05E286`) so in this case the /dev/sdX naming is much more comfortable.

The blue bar is not as simple a solution as enforcing 5px width because of Hi-DPI situations, but I'll try to find a way, this should be doable. I'm also investigating the ordering.

Regarding the "after" situation, there's nothing to show, because when autopartitioning on a legacy BIOS system we don't create a separate boot partition, the bootloader is just installed in the MBR and the summary page should report that.

**Comment by teo** [comment]
The bootloader setting now tracks the last chosen install disk.
