### ISSUE TITLE
[failed]: calamares failed to install on a system which had 2 x netrunner 16 on it

### ISSUE THREAD

**Issue by star-buck** [calamares/calamares-todos#20]
I manually replaced one of the partitions and reformatted it to ext4 with mountpoint /.
Error below:
![calamares3](https://cloud.githubusercontent.com/assets/840070/11791192/cf5d0dfe-a297-11e5-93cc-f99a2ce55816.png)

**Comment by philmmanjaro** [comment]
Did you setup EFI mode properly. Seems to be an user issue here. UEFI needs special partitioning.

**Comment by philmmanjaro** [comment]
Always use the debug mode and post a full install log so we can debug it more:
```
sudo calamares -d
```
Just screenshots won't help much.

**Comment by star-buck** [comment]
23:33:05 [1]: Calamares version: 1.80.0.r1654.8239e12 
Translation: Calamares: Using system locale: "en_US"
Translation: Qt: Using default locale, system locale one not found: "en_US"
23:33:05 [1]: Default font ===== 
Pixel size:    -1 
Point size:    9 
Point sizeF:   9 
Font family:   "Sans Serif" 
Metric height: 14 
23:33:05 [1]: Font height: 14 
23:33:05 [1]: Available languages: ("ar", "ast", "ca", "cs_CZ", "da", "de", "en", "en_GB", "es_MX", "es", "fi_FI", "fr", "hr", "hu", "id", "it_IT", "ja", "lt", "nl", "pl", "pt_BR", "pt_PT", "ro", "ru", "sk", "sl", "sv", "th", "tr_TR", "zh_CN", "zh_TW") 
23:33:05 [1]: CalamaresApplication thread: 0xa78ab0 
23:33:05 [1]: Using Calamares settings file at "/usr/share/calamares/settings.conf" 
23:33:05 [1]: Using Calamares branding file at "/usr/share/calamares/branding/manjaro/branding.desc" 
23:33:05 [1]: WARNING: the selected branding component does not ship translations. 
23:33:05 [1]: Loaded branding component "manjaro" 
23:33:05 [1]: Proposed window size: 1010 520 
23:33:05 [1]: Initial locale  "en_US" 
23:33:05 [8]: Translation: Calamares: Using system locale: "en_US"
23:33:05 [8]: Translation: Qt: Using default locale, system locale one not found: "en_US"
23:33:05 [1]: ViewModule loading self for instance "welcome@welcome" 
ViewModule at address 0xb23e90 
Calamares::PluginFactory at address WelcomeViewStepFactory(0xb60800) 
ViewStep at address WelcomeViewStep(0xc68500) 
23:33:05 [1]: ViewModule loading self for instance "locale@locale" 
ViewModule at address 0xca23b0 
Calamares::PluginFactory at address LocaleViewStepFactory(0xca1de0) 
ViewStep at address LocaleViewStep(0xca2840) 
No layout variant specified on the command line
Trailing -variant option ignored
23:33:05 [1]: xkbmap selection changed to:  "us" - "" 
23:33:05 [1]: ViewModule loading self for instance "keyboard@keyboard" 
ViewModule at address 0xdb1ef0 
Calamares::PluginFactory at address KeyboardViewStepFactory(0xca2c30) 
ViewStep at address KeyboardViewStep(0xdb41d0) 
23:33:05 [8]: Loaded backend plugin:  "pmlibpartedbackendplugin"
23:33:06 [0]: QFileInfo::absolutePath: Constructed with empty filename
23:33:06 [0]: QFileInfo::absolutePath: Constructed with empty filename
23:33:06 [0]: blkid: unknown file system type  ""  on  /dev/sda2
23:33:06 [0]: QFileInfo::absolutePath: Constructed with empty filename
23:33:06 [8]: getting smart status failed for  "/dev/sdb" :  Operation not supported
23:33:06 [1]: WARNING: system is EFI but no EFI system partitions found. 
23:33:06 [1]: ViewModule loading self for instance "partition@partition" 
ViewModule at address 0x2fd6200 
Calamares::PluginFactory at address PartitionViewStepFactory(0x2fc6580) 
ViewStep at address PartitionViewStep(0x2fdacf0) 
23:33:06 [1]: ViewModule loading self for instance "users@users" 
ViewModule at address 0xa7d880 
Calamares::PluginFactory at address UsersViewStepFactory(0xa7db10) 
ViewStep at address UsersViewStep(0x303f950) 
23:33:06 [1]: ViewModule loading self for instance "summary@summary" 
ViewModule at address 0x3071070 
Calamares::PluginFactory at address SummaryViewStepFactory(0x30716f0) 
ViewStep at address SummaryViewStep(0x30719b0) 
23:33:06 [1]: Module "partition@partition" already loaded. 
23:33:06 [1]: QML import paths: ("/usr/share/calamares/qml", "/usr/bin", "/usr/lib/qt/qml") 
23:33:06 [1]: LAST VS IS EVS! 
23:33:06 [1]: LAST VS IS EVS! 
23:33:06 [1]: LAST VS IS EVS! 
23:33:06 [1]: LAST VS IS EVS! 
23:33:06 [1]: Module "locale@locale" already loaded. 
23:33:06 [1]: LAST VS IS EVS! 
23:33:06 [1]: Module "keyboard@keyboard" already loaded. 
23:33:06 [1]: LAST VS IS EVS! 
23:33:06 [1]: LAST VS IS EVS! 
23:33:06 [1]: LAST VS IS EVS! 
23:33:06 [1]: LAST VS IS EVS! 
23:33:06 [1]: Module "users@users" already loaded. 
23:33:06 [1]: LAST VS IS EVS! 
23:33:06 [1]: LAST VS IS EVS! 
23:33:06 [1]: LAST VS IS EVS! 
23:33:06 [1]: LAST VS IS EVS! 
23:33:06 [1]: LAST VS IS EVS! 
23:33:06 [1]: LAST VS IS EVS! 
23:33:06 [1]: LAST VS IS EVS! 
23:33:06 [1]: LAST VS IS EVS! 
23:33:06 [1]: LAST VS IS EVS! 
23:33:06 [1]: LAST VS IS EVS! 
23:33:06 [1]: ViewModule loading self for instance "finished@finished" 
ViewModule at address 0x311f140 
Calamares::PluginFactory at address FinishedViewStepFactory(0x312e510) 
ViewStep at address FinishedViewStep(0x31232e0) 
23:33:06 [1]: Need at least storage bytes: 5905580032 
23:33:06 [1]: Need at least ram bytes: 1073741824 
23:33:06 [1]: enoughStorage, enoughRam, hasPower, hasInternet, isRoot:  true true true true true 
23:33:07 [1]: checking if "/dev/sda1" can be resized. 
23:33:07 [1]: "/dev/sda1" seems like a good path 
23:33:07 [1]: found Partition* for "/dev/sda1" 
23:33:07 [1]: Required  storage B: 8160437862 "(7GB)" 
23:33:07 [1]: Available storage B: 438024172032 "(407GB)" 
23:33:07 [1]: Partition "/dev/sda1" authorized for resize + autopartition install. 
23:33:07 [1]: checking if "/dev/sda3" can be resized. 
23:33:07 [1]: "/dev/sda3" seems like a good path 
23:33:07 [1]: found Partition* for "/dev/sda3" 
23:33:07 [1]: Required  storage B: 8160437862 "(7GB)" 
23:33:07 [1]: Available storage B: 480923070464 "(447GB)" 
23:33:07 [1]: Partition "/dev/sda3" authorized for resize + autopartition install. 
23:33:07 [1]: "Osprober lines, clean:\n/dev/sda1:Netrunner 16 (16):Ubuntu:linux\n/dev/sda3:Netrunner Rolling (next-dev3):Netrunner:linux" 
23:33:07 [1]: Updating partitioning state widgets. 
23:33:07 [0]: QCoreApplication::postEvent: Unexpected null receiver
23:33:08 [0]: QFileInfo::absolutePath: Constructed with empty filename
23:33:08 [0]: QFileInfo::absolutePath: Constructed with empty filename
23:33:08 [0]: blkid: unknown file system type  ""  on  /dev/sda2
23:33:08 [0]: QFileInfo::absolutePath: Constructed with empty filename
23:33:08 [1]: WARNING: system is EFI but there's no EFI system partition, DISABLING alongside and replace features. 
23:33:08 [1]: Updating partitioning preview widgets. 
23:33:08 [0]: QCoreApplication::postEvent: Unexpected null receiver
23:33:08 [1]: Current index changed: "/dev/sda1" 
23:33:08 [0]: QFileInfo::absolutePath: Constructed with empty filename
23:33:08 [0]: QFileInfo::absolutePath: Constructed with empty filename                                                                                                                                                                       
23:33:08 [0]: blkid: unknown file system type  ""  on  /dev/sda2                                                                                                                                                                             
23:33:08 [0]: QFileInfo::absolutePath: Constructed with empty filename                                                                                                                                                                       
23:33:08 [1]: PSI added item "/dev/sda1" size 495863202304                                                                                                                                                                                   
23:33:08 [1]: PSI added item "/dev/sda3" size 495864250368                                                                                                                                                                                   
23:33:08 [1]: PSI added item "/dev/sda2" size 8473543680                                                                                                                                                                                     
23:33:08 [1]: void PartitionSplitterWidget::setSplitPartition(const QString&, qint64, qint64, qint64, const QString&) path: "/dev/sda1"                                                                                                      
minSize: 63622933299                                                                                                                                                                                                                         
maxSize: 487702764442                                                                                                                                                                                                                        
prfSize: 247931601152                                                                                                                                                                                                                        
23:33:08 [1]: itemToResize: "/dev/sda1"                                                                                                                                                                                                      
23:33:08 [1]: Items updated. Status:                                                                                                                                                                                                         
23:33:08 [1]: item "/dev/sda1" size 247931601152                                                                                                                                                                                             
23:33:08 [1]: item "" size 247931601152                                                                                                                                                                                                      
23:33:08 [1]: item "/dev/sda3" size 495864250368                                                                                                                                                                                             
23:33:08 [1]: item "/dev/sda2" size 8473543680

**Comment by star-buck** [comment]
so I guess the culprit is:
23:33:08 [1]: WARNING: system is EFI but there's no EFI system partition, DISABLING alongside and replace features.

Nevertheless, it should still offer at least the replace option. Also the installer this time is from the manjaro live media, which is probably also not the super-latest, as its not showing the bios or uefi infos in the upper right corner.

**Comment by philmmanjaro** [comment]
Well, this feature is in the **calamares-exp** package for now. I released it with the [**xfce-dev** build](http://sourceforge.net/projects/manjarotest/files/15.12/xfce-minimal/15.12-dev/) last Saturday.

**Comment by teo** [comment]
I can't show the replace option if the system is booted in EFI mode but no EFI system partition can be found, because such an install might not boot. A reliable way to get to a booting EFI system from this kind of setup is a complete erase (which will automatically create an EFI system partition) or manually creating the EFI system partition in manual partitioning.
However I'm guessing your other systems have been installed in legacy BIOS mode? If that's the case I wonder why this system keeps booting as EFI from the live media.

**Comment by star-buck** [comment]
Exactly.
So even if it boots the LIVE session in EFI, if the installed systems are
legacy bios , it should offer replace, install alongside and simply let the
user choose to keep bios if doing so or install with erase an efi system.
