### ISSUE TITLE
[partition]: Preview bar refurbishment

### ISSUE THREAD

**Issue by star-buck** [calamares/calamares-todos#21]
Normally, when deleting everything, the system should show 2 partitions: main and swap.
But here it shows 4 with 2 not really visibly represented in bar:
![cala-part-1](https://cloud.githubusercontent.com/assets/840070/11798601/3005c304-a2c4-11e5-8703-88b266dfc4b1.png)

**Comment by teo** [comment]
I agree this is a bit confusing. It's not technically a bug, it just happens because the widget correctly calculates that on a 1TB disk, a 1MiB free space chunk and a 300MiB partition would be displayed as less than 1px wide in this bar.
There is a potential solution for this, it's logarithmic bar width calculation, but it might take me a while to implement it. Should I make this too a priority for 2.0?

**Comment by star-buck** [comment]
How about lets forget the 1 mb one and just label the 300mb correctly as
bootloader partition in the legend?

**Comment by teo** [comment]
Sure, I've been working on this and I've pushed several changes to the partition labels model/view as well as osprober handling today. I'll send you an updated screenshot for feedback, along with changes requested in issue #18 soon.

**Comment by star-buck** [comment]
Update:
After testing the beta1, here is further refurbishment:
![partman-1](https://cloud.githubusercontent.com/assets/840070/11916063/5a1ab2f6-a6bd-11e5-9692-7057d4f9d8cb.png)
![partman-3](https://cloud.githubusercontent.com/assets/840070/11916062/5a193bec-a6bd-11e5-806d-74f048db0e2a.png)

Lets move the hr-line below the 4 possible options, that is below the Manual Partitioning option.
So then any more text or manual selection is done or blend in / updated below that line, e.g. the todo text from the Replace option.

Further I assume that the alongside second page will be also merged into the main partition page below that line, where the user can select the partition to shrink and drag the size.

**Comment by teo** [comment]
![dsokcro](https://cloud.githubusercontent.com/assets/126364/11955439/48c7f008-a8b2-11e5-8e51-3c70b83ed95c.png)
Yes, the plan is to move the alongside widget to the ChoicePage too.

**Comment by star-buck** [comment]
after another testround, please eliminate any logical extended partitions in the preview bar (the grey ones).
It is less confusing and less error prone, see example of people picking this to replace and ending up with no swap...
![screenshot_20160111_141223](https://cloud.githubusercontent.com/assets/840070/12235787/e68b41bc-b86d-11e5-8d44-8cab726e934d.png)

it is not shown in ubiquity either, and apparently no one missed it.
