### ISSUE TITLE
[reports]: Apricity OS failed to install GRUB in this (admittedly complex) review scenario

### ISSUE THREAD

**Issue by star-buck** [calamares/calamares-todos#23]
Scroll down to the bottom part:
http://www.dedoimedo.com/computers/apricity-os-12-2015.html

Conclusion:
Let's get Calamares 2.0 ready, so the nice early adoption of 1.x doesn't start to hurt Calamares and the distros shipping it!

**Comment by philmmanjaro** [comment]
To be frank. Calamares 2.0 series was used on Apricity OS. You can see that on the partitioning layout. Sadly you can't make out which exact version they used ...

**Comment by star-buck** [comment]
closing this since 2.0 released
