### ISSUE TITLE
[summary]: wants to install on sda AND sdb (usb stick)

### ISSUE THREAD

**Issue by star-buck** [calamares/calamares-todos#24]
I tested the "choose storage device" and selected sdb and then back to sda to continue the installation on harddisk.

Apparently its good to have a summary, as it revealed it would going to install Netrunner on sdb as well as sda, even though I did go back to sda and then clicked continue:
![screenshot_20160130_144521](https://cloud.githubusercontent.com/assets/840070/12696381/c831d5ea-c769-11e5-9172-de088b57d9c7.png)

**Comment by teo** [comment]
Should be fixed in current master.

**Comment by star-buck** [comment]
closing this here since 2.0 released
