### ISSUE TITLE
[restart now] option has no effect (neither ISO nor IMG)

### ISSUE THREAD

**Issue by star-buck** [calamares/calamares-todos#28]
even when ticked, calamares doesnt restart.

**Comment by teo** [comment]
The restart command to be executed is entirely dependent on the config file of the `finished` module, for instance for me it works on a correctly configured Manjaro-KDE.
Have you encountered this bug on Netrunner Debian ISOs?

**Comment by star-buck** [comment]
yes, so ill close ticket here and write one for debian team.
