### ISSUE TITLE
[manual partitioning]: show installed systems of colored partitions like on main page before

### ISSUE THREAD

**Issue by star-buck** [calamares/calamares-todos#31]
main page:
![screenshot_20160622_190945](https://cloud.githubusercontent.com/assets/840070/16280184/aca551f0-38be-11e6-8c4d-86c2496f129c.png)
manual listing:
![screenshot_20160622_191341](https://cloud.githubusercontent.com/assets/840070/16280190/b3313fc0-38be-11e6-92ce-8276478744de.png)

suggestion: show partition system names legend above the white box for all the colored partitions

**Comment by teo** [comment]
Fixed in master.
