### ISSUE TITLE
Create a slideshow for the installing phase

### ISSUE THREAD

**Issue by star-buck** [calamares/calamares-todos#4]
Could be QML or HTML? Must be brandable. Suggestions and/or help accepted.

**Comment by star-buck** [comment]
comment by plfiorini:

Some people might prefer HTML other might want a bunch of images.
HTML and QML are not mutually exclusive, if this page is implemented with QML one can provide qml files for branding and do whatever he wants even HTML. We can provide a couple of default QML implementations: one that uses WebKit and another one that does a slideshow from a directory provided by the distro.

**Comment by teo** [comment]
This is now implemented with QML, and KaOS and Manjaro have already taken it up and are putting together their slideshows. With the Calamares QML slideshow system, it is also easy to just load a bunch of pictures as a legacy solution, so I believe most use cases are satisfied. If need arises for a HTML reimplementation, I propose that it is dealt with as a separate task post-1.0.
