### ISSUE TITLE
Add to Calamares the abitily to run in Command Line mode

### ISSUE THREAD

**Issue by dertasiu** [calamares/calamares-todos#8]
I would like to know if there is planed to do a CLI mode for Calamares or if it has been done.
Thank you.

**Comment by teo** [comment]
This idea is on the table, but it's not a short term focus right now. One would probably have to take libcalamares, and then develop a non-interactive mode and/or a ncurses interface on top of it. It is an interesting project, and I'd definitely like to see it done at some point.

**Comment by dertasiu** [comment]
Oh, ok.
Thank you for answering : )

**Comment by teo** [comment]
Moved to Calamares [issue tracker](https://calamares.io/bugs/browse/CAL-378).
