### ISSUE TITLE
Entropy & Portage backends

### ISSUE THREAD

**Issue by necrose99** [calamares/calamares-todos#9]
https://github.com/Sabayon/entropy

equo update & Equo install foo... Sabayon is a binary /Gentoo 
works simularly to rpm deb etc,

**Comment by teo** [comment]
I've recreated this task in our actual issue tracker http://calamares.io/bugs/browse/CAL-204

Unfortunately we don't have contributors from Sabayon yet, but you can be the first. Check out https://github.com/calamares/calamares/blob/master/src/modules/packages/main.py if you'd like to add the relevant commands to support Sabayon, we would welcome a pull request.

**Comment by necrose99** [comment]
ok np spike-pentesting were a fork , we tried to stay in house but we got the hand... 
I'll do my best with my limited prog skills....
